import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const desktop = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const root = resolve(desktop, '..')
const runtime = resolve(desktop, 'runtime')
const outdir = resolve(runtime, 'lib')
const config = resolve(runtime, 'config')
const deployDir = resolve(desktop, 'src-tauri/resources/runtime')

await rm(outdir, { recursive: true, force: true })
await rm(config, { recursive: true, force: true })
await mkdir(outdir, { recursive: true })
await cp(resolve(root, 'apps/cli/config'), config, { recursive: true })
await writeProfileBootBridge()
await writeBridgeScriptModule()
await stageClientUiBundle()

const common = {
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'esm',
  packages: 'external',
  external: ['@deepseek-ai/*'],
  sourcemap: true,
  logLevel: 'info',
}

await build({
  ...common,
  entryPoints: {
    sidecar: resolve(runtime, 'src/sidecar.ts'),
    surface: resolve(runtime, 'src/surface.ts'),
    'directory-picker': resolve(runtime, 'src/directory-picker.ts'),
    'api-gateway': resolve(runtime, 'src/api-gateway.ts'),
  },
  outdir,
  entryNames: '[name]',
  chunkNames: 'chunks/[name]-[hash]',
  outExtension: { '.js': '.mjs' },
  splitting: true,
})

await rm(deployDir, { recursive: true, force: true })

async function writeProfileBootBridge() {
  const cliLib = resolve(root, 'apps/cli/lib')
  const candidates = (await readdir(cliLib))
    .filter(name => /^profile-boot-.+\.js$/.test(name))
  const facades = []
  for (const name of candidates) {
    const source = await readFile(resolve(cliLib, name), 'utf8')
    if (/export\s*\{\s*runProfile\s*\}/.test(source)) facades.push(name)
  }
  if (facades.length !== 1) {
    throw new Error(`expected one built dsh profile-boot facade, found ${facades.length}`)
  }
  const specifier = `../node_modules/@deepseek-ai/dsh/lib/${facades[0]}`
  await writeFile(resolve(outdir, 'profile-boot.mjs'), `export { runProfile } from ${JSON.stringify(specifier)}\n`)
}

/**
 * Stage the desktop-only client UI bundle (the About section + update badge):
 * the source is hand-written in the `window.__ModuleLoader__.load` contract
 * (same format the harness serves for every dsh.client package) and ships
 * verbatim as lib/client.js of @deepseek-ai/dsh-desktop-client-ui.
 */
async function stageClientUiBundle() {
  const source = resolve(desktop, 'client-ui/src')
  const target = resolve(desktop, 'client-ui/lib')
  await rm(target, { recursive: true, force: true })
  await mkdir(target, { recursive: true })
  await Promise.all([
    cp(resolve(source, 'index.js'), resolve(target, 'index.js')),
    cp(resolve(source, 'client.js'), resolve(target, 'client.js')),
  ])
  process.stdout.write('staged desktop client-ui host and client bundles\n')
}

/**
 * Bundle the page-side bridge (the one desktop affordance the frontend needs)
 * and inline the minified IIFE as a text module the desktop-surface plugin
 * serves and injects through the web host's own index taps.
 */
async function writeBridgeScriptModule() {
  const result = await build({
    entryPoints: [resolve(desktop, 'bridge/src/index.ts')],
    bundle: true,
    platform: 'browser',
    target: ['safari15', 'chrome105'],
    format: 'iife',
    minify: true,
    write: false,
    logLevel: 'info',
  })
  const bridgeSource = result.outputFiles[0].text
  await writeFile(
    resolve(runtime, 'src/bridge-script.generated.ts'),
    `// generated by desktop/scripts/build-runtime.mjs — do not edit\nexport const bridgeScript = ${JSON.stringify(bridgeSource)}\n`,
  )
}
